# Generated by Django 3.0.2 on 2020-02-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.TextField(blank=True, null=True)),
                ('mobile', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('billing_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('final_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
