# Generated by Django 3.0.2 on 2020-02-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.TextField()),
                ('address', models.TextField()),
                ('delivery_date', models.DateField()),
                ('item', models.TextField()),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('paid_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
