# Generated by Django 3.0.2 on 2020-02-08 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='billing_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
