# Generated by Django 3.0.2 on 2020-02-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200208_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
